absl-py==1.4.0
addict==2.4.0
aiofiles==22.1.0
aiosqlite==0.19.0
anyio==3.7.0
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arrow==1.2.3
asttokens==2.2.1
Babel==2.12.1
backcall==0.2.0
beautifulsoup4==4.12.2
black==23.3.0
cachetools==3.1.0
certifi==2023.7.22
charset-normalizer==3.1.0
click==8.1.3
colorama==0.4.6
comm==0.1.3
contourpy==1.1.0
cycler==0.11.0
Cython==0.29.36
debugpy==1.6.7
decorator==5.1.1
defusedxml==0.7.1
deprecation==2.1.0
descartes==1.1.0
exceptiongroup==1.1.1
executing==1.2.0
fastjsonschema==2.17.1
filelock==3.12.4
fire==0.5.0
flake8==6.0.0
fonttools==4.40.0
fqdn==1.5.1
fsspec==2023.9.2
future==0.18.3
gnureadline==8.1.2
google-auth==2.21.0
google-auth-oauthlib==1.0.0
grpcio==1.56.0
h5py==3.9.0
huggingface-hub==0.17.2
idna==3.4
imageio==2.31.1
importlib-metadata==6.7.0
iniconfig==2.0.0
ipykernel==6.25.0
ipython==8.12.2
ipython-genutils==0.2.0
isoduration==20.11.0
jedi==0.19.0
joblib==1.3.1
json5==0.9.14
jsonpointer==2.4
torch==1.10.1
jupyter==1.0.0
jupyter-events==0.6.3
jupyter-packaging==0.10.0
jupyter-ydoc==0.2.4
jupyter_client==8.3.0
jupyter_core==5.3.1
jupyter_server==2.7.0
jupyter_server_fileid==0.9.0
jupyter_server_terminals==0.4.4
jupyter_server_ydoc==0.8.0
jupyterlab_server==2.23.0
kiwisolver==1.4.4
lazy_loader==0.2
llvmlite==0.36.0
lmdb==1.4.1
loguru==0.7.0
lyft-dataset-sdk==0.0.8
Markdown==3.4.3
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.5.2
matplotlib-inline==0.1.6
mccabe==0.7.0
mdurl==0.1.2
mmcv==1.4.0
mmcv-full==1.4.0
mmengine==0.7.4
mmsegmentation==0.20.1
model-index==0.1.11
mpi4py==3.0.3
msgpack==1.0.5
msgpack-numpy==0.4.8
multimethod==1.9.1
mypy-extensions==1.0.0
nbclassic==1.0.0
nest-asyncio==1.5.7
networkx==2.2
notebook_shim==0.2.3
numba==0.53.0
numpy==1.20.3
nuscenes-devkit==1.1.10
oauthlib==3.2.2
opencv-python==4.8.0.74
ordered-set==4.1.0
overrides==7.3.1
packaging==23.1
palettable==3.3.3
pandas==2.0.2
pandocfilters==1.5.0
parso==0.8.3
pathspec==0.11.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.4.0
pkgutil_resolve_name==1.3.10
platformdirs==3.8.0
plotly==5.15.0
pluggy==1.2.0
plyfile==0.9
prettytable==3.8.0
prompt-toolkit==3.0.39
protobuf==3.19.6
psutil==5.9.5
ptyprocess==0.7.0
pure-eval==0.2.2
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycocotools==2.0.6
pycodestyle==2.10.0
pycparser==2.21
pycryptodome==3.18.0
pyflakes==3.0.1
Pygments==2.15.1
pyparsing==3.1.0
pyquaternion==0.9.9
pytest==7.4.0
python-dateutil==2.8.2
python-json-logger==2.0.7
pytz==2023.3
PyWavelets==1.4.1
PyYAML==6.0
pyzmq==25.1.0
readline==6.2.4.1
requests==2.31.0
requests-oauthlib==1.3.1
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rich==13.4.2
rsa==4.9
safetensors==0.3.3
scikit-image==0.19.3
scikit-learn==1.3.0
scipy==1.10.1
seaborn==0.12.2
Shapely==1.8.5
six==1.16.0
sniffio==1.3.0
soupsieve==2.4.1
stack-data==0.6.2
tabulate==0.9.0
tb-nightly==2.14.0a20230629
tenacity==8.2.2
tensorboard-data-server==0.7.1
tensorpack==0.11
termcolor==2.3.0
terminaltables==3.1.10
threadpoolctl==3.1.0
tifffile==2023.4.12
timm==0.9.7
tinycss2==1.2.1
toml==0.10.2
tomli==2.0.1
tomlkit==0.11.8
torch-tb-profiler==0.4.1
torchaudio==0.10.1
torchpack==0.3.1
torchvision==0.11.2
tornado==6.3.2
tqdm==4.65.0
traitlets==5.9.0
trimesh==2.35.39
typing_extensions==4.7.1
tzdata==2023.3
uri-template==1.3.0
urllib3==1.26.16
wcwidth==0.2.6
webcolors==1.13
webencodings==0.5.1
websocket-client==1.6.1
Werkzeug==2.3.6
yapf==0.40.1
zipp==3.15.0
setuptools==59.5.0
